services:
  - type: web
    name: ai-voice-calling-backend
    runtime: python3
    buildCommand: "pip install -r requirements.txt && python -m prisma py fetch && python -m prisma generate --schema=./prisma/schema.prisma"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: PRISMA_CLI_BINARY_TARGETS
        value: debian-openssl-3.0.x
      - key: PRISMA_QUERY_ENGINE_BINARY
        value: debian-openssl-3.0.x
      - key: SUPABASE_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUBSPOT_ACCESS_TOKEN
        sync: false
      - key: REDIS_HOST_URI
        sync: false
      - key: REDIS_PASS
        sync: false
      - key: BASE_URL
        sync: false
