services:
  - type: web
    name: ai-voice-calling-backend
    runtime: python3
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && python main.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: SUPABASE_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUBSPOT_ACCESS_TOKEN
        sync: false
      - key: REDIS_HOST_URI
        sync: false
      - key: REDIS_PASS
        sync: false
      - key: BASE_URL
        sync: false
